services:
  database:
    image: mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: '1111'
      MYSQL_DATABASE: crmproject
      MYSQL_USER: crmproject
      MYSQL_PASSWORD: 1111
    networks:
      - crm-network
  app:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - crm-network
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:mysql://database/crmproject?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true'
      JAKARTA_PERSISTENCE_JDBC_URL: 'jdbc:mysql://database/crmproject?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true'
    depends_on:
      - database

networks:
  crm-network:
    driver: bridge