name : CI/CD
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Grant execute permission for gradle
        run: chmod +x gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Check current directory contents
        run: ls -l

      - name: Grant execute permission for docker-compose
        run: chmod +x docker-compose.yaml

      - name: Stop app service
        run: docker-compose -f docker-compose.yaml stop app

      - name: Stop database service
        run: docker-compose -f docker-compose.yaml stop database

      - name: docker-compose down
        run: docker-compose down

      - name: Build with Gradle
        run: ./gradlew clean bootJar

      - name: Get current time
        uses: josStorer/get-current-time@v2.0.2
        id: current-time
        with:
          format: YYYY-MM-DDTHH-mm-ss
          utcOffset: "+9:00"

      - name: Set artifact
        run: echo "artifact=$(ls ./build/libs)" >> $GITHUB_ENV

      - name: Start database service
        run: docker-compose -f docker-compose.yaml up -d database

      - name: Start app service
        run: docker-compose -f docker-compose.yaml up -d app
